include(
    ":logging",
    ":logging-android",
    ":logging-android-firebase",
    ":logging-android-appcenter",
    ":logging-android-appcenter3",
    ":logging-android-datadog",
    ":kotlin-testapp",
    ":java-testapp",
    ":android-loggingtestapp"
)
