include(
    ":logging",
    ":logging-test",
    ":logging-android",
    ":logging-android-firebase",
    ":logging-android-appcenter3",
    ":logging-android-datadog",
    ":logging-android-newrelic",
    ":logging-android-urbanairship",
    ":kotlin-testapp",
    ":java-testapp",
    ":android-loggingtestapp"
)
